# Plugins
whitelist: ["jekyll-relative-links"]
plugins: ["jekyll-relative-links"]
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
sidebar:
  - label: Table of contents
    children:
      - GettingStarted
      - Unity
      - MatlabSimulink
